#pragma once
#include <Windows.h>
#include <iostream>  
#include <vector>  
#include <bitset>  
#include <array>  
#include <string>  
#include <intrin.h> 
#include <tlhelp32.h>
#include <ntstatus.h>
#include <winternl.h>
#include <Shlwapi.h>
#include <cassert>
#include <malloc.h>
#include <vector>
#include <algorithm>
#include <iosfwd>
#include <sstream>
#include <psapi.h>
#include <map>
#include <cctype>
